import type { ConceptRevisionContent } from "./types";

export const idempotency: ConceptRevisionContent = {
  slug: "idempotency",
  title: "Idempotency",
  topic: "Architecture",
  difficulty: "Advanced",
  estimatedMinutes: 15,
  docLinks: [
    { label: "Retry Mechanisms", href: "/docs/microservices/retry" },
    { label: "Message Queues", href: "/docs/messaging/queues" },
  ],
  summary: [
    "Idempotency ensures that performing an operation multiple times yields the same result as performing it exactly once.",
    "In distributed systems, networks are unreliable, making retries necessary. Idempotency makes retries safe.",
    "Without idempotency, a retried payment request might charge a customer twice.",
    "It is typically implemented using Idempotency Keys passed by the client.",
    "The server tracks these keys and returns the cached response if it detects a duplicate request.",
  ],
  whyAsked: [
    "To see if you understand the realities of distributed networks (network partitions, timeouts).",
    "To evaluate how you design safe APIs for critical operations (like payments or state mutations).",
    "To test your knowledge of exactly-once semantics and duplicate processing.",
  ],
  thirtySecondAnswer: "Idempotency is a property of an operation where applying it multiple times has the same effect as applying it once. In distributed systems, temporary network failures mean clients often receive timeouts without knowing if the server processed their request. They must retry. If the operation is creating a payment, retrying without idempotency could charge the user twice. We solve this by having the client generate a unique Idempotency Key (like a UUID) for the transaction. The server checks this key: if it's new, it processes the payment; if it's already seen, it simply returns the cached success response of the original attempt.",
  detailedAnswer: [
    "HTTP methods like GET, PUT, and DELETE are idempotent by definition. POST is not.",
    "Clients must generate and attach a unique 'Idempotency-Key' header to state-changing requests.",
    "The server checks a fast datastore (like Redis or a dedicated DB table) for the presence of the key.",
    "If the key exists and the operation is complete, the server returns the cached response.",
    "If the key exists and the operation is in-progress, the server rejects the request or makes the client wait, preventing race conditions.",
    "Idempotency keys should have a Time-To-Live (TTL), usually 24 hours, so the datastore doesn't grow indefinitely.",
  ],
  questions: [
    { id: "idem-q1", question: "What does it mean for an operation to be idempotent?", answer: "It means executing the operation multiple times produces the same result and side effects as executing it once.", topic: "Architecture", difficulty: "Beginner" },
    { id: "idem-q2", question: "Why is idempotency critical in distributed systems?", answer: "Because networks are unreliable. Clients must retry failed or timed-out requests, and idempotency ensures retries are safe.", topic: "Architecture", difficulty: "Beginner" },
    { id: "idem-q3", question: "Which HTTP methods are naturally idempotent?", answer: "GET, PUT, DELETE, HEAD, and OPTIONS.", topic: "Architecture", difficulty: "Beginner" },
    { id: "idem-q4", question: "Is HTTP POST idempotent?", answer: "No. Calling POST multiple times typically creates multiple resources.", topic: "Architecture", difficulty: "Beginner" },
    { id: "idem-q5", question: "What is an Idempotency Key?", answer: "A unique identifier (usually a UUID) generated by the client and sent with a request to identify retries.", topic: "Architecture", difficulty: "Beginner" },
    { id: "idem-q6", question: "How does a server use an Idempotency Key?", answer: "It checks if the key was previously processed. If yes, it returns the cached result. If no, it processes the request and saves the result against the key.", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-q7", question: "What happens if a client receives a network timeout when making a payment?", answer: "The client doesn't know if the payment succeeded. It retries the request using the same Idempotency Key.", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-q8", question: "What should the server do if it receives a request with an Idempotency Key that is currently being processed by another thread?", answer: "It should return a 409 Conflict or a custom 'Processing' status to prevent race conditions (double execution).", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-q9", question: "Where should Idempotency Keys be stored?", answer: "In a fast, highly available store like Redis, or in a database alongside the transactional data to ensure atomicity.", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-q10", question: "Should Idempotency Keys be kept forever?", answer: "No, they should have a TTL (Time-To-Live), typically 24-48 hours, to prevent the datastore from growing infinitely.", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-q11", question: "What if a client alters the request payload but uses the same Idempotency Key?", answer: "The server should detect the payload mismatch and reject the request with an error (e.g., 400 Bad Request).", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-q12", question: "How does idempotency relate to 'At-Least-Once' delivery in message queues?", answer: "Message queues often guarantee 'at-least-once' delivery, meaning duplicates can occur. Consumers must be idempotent to handle duplicates safely.", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-q13", question: "How can you implement idempotency using a relational database?", answer: "By using the Idempotency Key as a unique constraint on a dedicated table. Attempting to insert a duplicate will throw a constraint violation.", topic: "Architecture", difficulty: "Advanced" },
    { id: "idem-q14", question: "What is the difference between Idempotency and Exactly-Once Processing?", answer: "Exactly-Once is a system guarantee (often very hard to achieve). Idempotency is a design pattern applied to the receiver to simulate exactly-once semantics over at-least-once infrastructure.", topic: "Architecture", difficulty: "Advanced" },
    { id: "idem-q15", question: "How does Stripe implement idempotency?", answer: "Stripe requires clients to send an 'Idempotency-Key' header for mutations. They save the response of the first request and replay it for 24 hours if the key is reused.", topic: "Architecture", difficulty: "Advanced" },
    { id: "idem-q16", question: "What is a 'natural' idempotency key?", answer: "A key derived from the data itself (e.g., OrderID + Status) rather than a randomly generated UUID.", topic: "Architecture", difficulty: "Advanced" },
    { id: "idem-q17", question: "Can a database UPDATE statement be non-idempotent?", answer: "Yes. 'UPDATE balance = balance + 10' is NOT idempotent. 'UPDATE balance = 50' IS idempotent.", topic: "Architecture", difficulty: "Advanced" },
    { id: "idem-q18", question: "How does optimistic concurrency control relate to idempotency?", answer: "Using version numbers (e.g., updating a record only if version = 5) naturally enforces idempotency for specific updates.", topic: "Architecture", difficulty: "Advanced" },
    { id: "idem-q19", question: "What is the two-phase nature of saving idempotent responses?", answer: "The server must first claim the key (lock), execute the business logic, and finally update the key with the final response payload.", topic: "Architecture", difficulty: "Advanced" },
    { id: "idem-q20", question: "How do you handle a server crash immediately after processing the request but before saving the idempotent result?", answer: "Using a distributed transaction or the Outbox pattern ensures the business entity and the idempotency record are committed atomically.", topic: "Architecture", difficulty: "Advanced" },
  ],
  commonFollowUps: [
    "How do you handle race conditions when two identical requests arrive at the exact same time?",
    "What happens if the client changes the request body but sends the same idempotency key?",
    "Where exactly in your architecture do you store the idempotency keys?",
  ],
  commonMistakes: [
    "Thinking that checking 'if user exists' before creating is enough (it causes race conditions).",
    "Storing keys indefinitely, causing memory/storage bloat.",
    "Allowing clients to reuse an idempotency key with a completely different request payload.",
  ],
  interviewTraps: [
    "Assuming networks are reliable and retries aren't needed.",
    "Not handling the 'in-progress' state of an idempotent request, leading to double execution if retried too quickly.",
  ],
  tradeoffs: [
    "Guarantees safe retries vs. Adds complexity to the server implementation.",
    "Prevents duplicate processing vs. Requires additional storage for keys and responses.",
    "Provides seamless client experience vs. Requires clients to actively manage key generation.",
  ],
  memoryTrick: "Idempotency is like an Elevator Button: Pressing it once calls the elevator. Pressing it 10 more times in a panic doesn't summon 10 elevators.",
  realWorldExamples: [
    "Payment Gateways: Stripe uses Idempotency-Key headers to ensure a user isn't double-charged if the app re-sends the payment request.",
    "Message Consumers: A Kafka consumer reading an 'OrderShipped' event must be idempotent in case Kafka delivers the message twice.",
  ],
  mermaidDiagram: `sequenceDiagram
    participant Client
    participant API
    participant Cache/DB
    Client->>API: POST /charge (Idempotency-Key: 123)
    API->>Cache/DB: Check Key 123
    Cache/DB-->>API: Not Found
    API->>Cache/DB: Lock Key 123 (Status: Processing)
    API->>API: Process Payment
    API->>Cache/DB: Update Key 123 (Status: Success, Response: {...})
    API-->>Client: 200 OK
    Note over Client: Network timeout, Client retries
    Client->>API: POST /charge (Idempotency-Key: 123)
    API->>Cache/DB: Check Key 123
    Cache/DB-->>API: Found (Status: Success, Response: {...})
    API-->>Client: 200 OK (Cached Response)
  `,
  flashcards: [
    { id: "idem-fc1", front: "What is Idempotency?", back: "The property where performing an operation multiple times has the same outcome as performing it exactly once.", topic: "Architecture", difficulty: "Beginner" },
    { id: "idem-fc2", front: "Why are Idempotency Keys necessary for POST requests?", back: "Because POST is not naturally idempotent, so a unique key is needed to detect and prevent duplicate executions during retries.", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-fc3", front: "How should a server handle a request if the Idempotency Key is currently marked as 'processing'?", back: "Return a 409 Conflict or block until processing completes to prevent race conditions.", topic: "Architecture", difficulty: "Advanced" },
    { id: "idem-fc4", front: "Who generates the Idempotency Key?", back: "The Client generates it so that retries of the same intent carry the exact same key.", topic: "Architecture", difficulty: "Intermediate" },
    { id: "idem-fc5", front: "What is the difference between exactly-once delivery and idempotency?", back: "Exactly-once is a network/system guarantee. Idempotency is a design pattern that makes at-least-once delivery behave safely like exactly-once.", topic: "Architecture", difficulty: "Advanced" },
  ],
  cheatSheet: {
    title: "Implementing Idempotency",
    sections: [
      {
        heading: "Idempotency Flow",
        items: [
          "1. Read key from request.",
          "2. If exists & done -> Return cached response.",
          "3. If exists & processing -> Return 409 Conflict.",
          "4. If new -> Lock key, process, save result.",
        ],
      },
      {
        heading: "Best Practices",
        items: [
          "Keys should be generated by clients.",
          "Validate request payload hash matches the original payload for the key.",
          "Use a TTL (e.g., 24 hours) for stored keys.",
          "Store the HTTP status code and response body with the key.",
        ],
      },
      {
        heading: "HTTP Methods",
        items: [
          "Idempotent: GET, PUT, DELETE",
          "NOT Idempotent: POST, PATCH (usually)",
        ],
      },
    ],
  },
  speedNotes: [
    "Makes retries safe.",
    "Multiple calls = one effect.",
    "Client generates unique UUID key.",
    "Server caches initial response.",
    "Crucial for payment processing.",
  ],
};
