import type { ConceptRevisionContent } from "./types";

export const logging: ConceptRevisionContent = {
  slug: "logging",
  title: "Logging",
  topic: "Observability",
  difficulty: "Beginner",
  estimatedMinutes: 10,
  docLinks: [
    { label: "Logging", href: "/docs/observability/logging" },
    { label: "Monitoring", href: "/docs/observability/monitoring" }
  ],
  summary: [
    "Logging is the practice of recording events, errors, and system state changes over time.",
    "Logs are crucial for debugging, auditing, and understanding what happened during an incident.",
    "Structured logging (e.g., JSON) makes it easier to parse, search, and analyze log data at scale.",
    "Log levels (INFO, DEBUG, ERROR, etc.) help filter the noise and prioritize critical issues.",
    "In distributed systems, centralized logging and trace IDs are necessary to follow a request across services."
  ],
  whyAsked: [
    "To see if you understand how to make a system debuggable and maintainable in production.",
    "To evaluate your knowledge of observability best practices (structured logging, log levels).",
    "To discuss the cost and performance implications of generating massive amounts of log data."
  ],
  thirtySecondAnswer: "Logging involves writing discrete event records to a storage system to track application behavior, errors, and user activities. Good logging practices use structured formats like JSON, include contextual information like request IDs, and utilize appropriate severity levels. In modern architectures, logs from various microservices are aggregated into a centralized logging system (like the ELK stack) for easy searching and correlation during incident response.",
  detailedAnswer: [
    "Logs provide a historical, timestamped record of events, which is essential for post-mortem analysis.",
    "Structured logs (key-value pairs or JSON) allow automated tools to easily index and query log fields.",
    "Common log levels include TRACE, DEBUG, INFO, WARN, ERROR, and FATAL.",
    "Centralized logging aggregates logs from multiple servers into a single searchable interface.",
    "High-volume logging can degrade application performance (I/O bottlenecks) and incur significant storage costs."
  ],
  questions: [
    { id: "log-q1", question: "What is logging in software development?", answer: "The process of recording events and messages generated by an application to track its operation and state.", topic: "Observability", difficulty: "Beginner" },
    { id: "log-q2", question: "Why is logging important?", answer: "It provides the necessary context to debug issues, monitor application health, and audit security events.", topic: "Observability", difficulty: "Beginner" },
    { id: "log-q3", question: "What are common log levels?", answer: "DEBUG, INFO, WARN, ERROR, FATAL.", topic: "Observability", difficulty: "Beginner" },
    { id: "log-q4", question: "What is structured logging?", answer: "Writing logs in a machine-readable format (like JSON) instead of plain text, allowing easy querying of specific fields.", topic: "Observability", difficulty: "Beginner" },
    { id: "log-q5", question: "What is the difference between logging and metrics?", answer: "Logs are detailed records of specific events; metrics are aggregated numbers (like counts or averages) over time.", topic: "Observability", difficulty: "Beginner" },
    { id: "log-q6", question: "What is centralized logging?", answer: "Gathering logs from multiple distributed services into a single unified system (like ELK/Datadog) for analysis.", topic: "Observability", difficulty: "Intermediate" },
    { id: "log-q7", question: "Why use structured logging over unstructured text logs?", answer: "Unstructured logs require fragile regex parsing. Structured logs allow instant querying, filtering, and indexing on key-value pairs.", topic: "Observability", difficulty: "Intermediate" },
    { id: "log-q8", question: "What is log rotation?", answer: "The process of archiving old logs and creating new log files to prevent logs from consuming all available disk space.", topic: "Observability", difficulty: "Intermediate" },
    { id: "log-q9", question: "How do you track a request across microservices?", answer: "By injecting a unique Correlation ID (or Trace ID) at the entry point and including it in all logs generated by downstream services for that request.", topic: "Observability", difficulty: "Intermediate" },
    { id: "log-q10", question: "What is the ELK stack?", answer: "Elasticsearch (storage/search), Logstash (processing/routing), and Kibana (visualization) — a popular centralized logging solution.", topic: "Observability", difficulty: "Intermediate" },
    { id: "log-q11", question: "What should NOT be logged?", difficulty: "Intermediate", topic: "Observability", answer: "PII (Personally Identifiable Information), passwords, credit card numbers, and secret tokens/API keys." },
    { id: "log-q12", question: "What is log sampling?", difficulty: "Intermediate", topic: "Observability", answer: "Recording only a percentage of logs (e.g., 10% of HTTP 200 OKs) to reduce storage costs and network bandwidth, while keeping 100% of errors." },
    { id: "log-q13", question: "How does logging impact system performance?", difficulty: "Intermediate", topic: "Observability", answer: "Synchronous disk I/O or network calls for logging can block the main application thread, increasing latency." },
    { id: "log-q14", question: "How do you mitigate the performance impact of logging?", difficulty: "Advanced", topic: "Observability", answer: "Use asynchronous logging, buffer logs in memory, write sequentially to disk, or offload log shipment to a sidecar agent." },
    { id: "log-q15", question: "How does the ELK stack handle high ingestion rates?", difficulty: "Advanced", topic: "Observability", answer: "By placing a message queue (like Kafka or Redis) in front of Logstash to buffer log events during traffic spikes." },
    { id: "log-q16", question: "What is log scrubbing?", difficulty: "Advanced", topic: "Observability", answer: "The automated process of masking or removing sensitive data (like SSNs or passwords) from log streams before they are stored." },
    { id: "log-q17", question: "Explain log levels in production vs. development.", difficulty: "Advanced", topic: "Observability", answer: "Dev often uses DEBUG/TRACE for verbose output. Prod usually restricts to INFO or WARN to save storage, dynamically enabling DEBUG only during active incidents." },
    { id: "log-q18", question: "What is a Sidecar logging pattern?", difficulty: "Advanced", topic: "Observability", answer: "Deploying a logging agent (like Fluentd) in a separate container next to the app container to handle log collection and forwarding transparently." },
    { id: "log-q19", question: "How do you handle logs in a Serverless environment?", difficulty: "Advanced", topic: "Observability", answer: "Serverless platforms (like AWS Lambda) typically auto-capture stdout/stderr and forward them to a managed service (like CloudWatch) asynchronously." },
    { id: "log-q20", question: "Why might you use vector clocks or logical clocks in distributed logs?", difficulty: "Advanced", topic: "Observability", answer: "Because physical clocks across distributed servers drift; logical clocks help determine the exact causal ordering of events." }
  ],
  commonFollowUps: [
    "How do you ensure logging doesn't become a bottleneck?",
    "How do you handle regulatory requirements (GDPR/HIPAA) regarding log data?",
    "What is the difference between logs, metrics, and traces?"
  ],
  commonMistakes: [
    "Logging sensitive user data (passwords, credit cards) in plain text.",
    "Using synchronous logging in the critical path, slowing down request handling.",
    "Logging as unstructured text string concatenation instead of structured JSON."
  ],
  interviewTraps: [
    "Relying solely on logs for monitoring. (Metrics are better for alerting; logs are for debugging).",
    "Assuming logs are strictly ordered across different servers without clock synchronization or logical clocks."
  ],
  tradeoffs: [
    "Verbosity vs. Storage Cost/Performance.",
    "Synchronous Logging (guaranteed capture) vs. Asynchronous Logging (better application performance).",
    "Centralized Logging (easy analysis) vs. Network Bandwidth usage."
  ],
  memoryTrick: "Logs are the 'Black Box' of your application flight; structured logs are the neatly labeled transcripts.",
  realWorldExamples: [
    "Using Splunk or Datadog to aggregate terabytes of JSON logs, allowing engineers to query 'error_code: 500' across all microservices instantly.",
    "A retail app scrubbing credit card numbers from raw HTTP request logs before pushing them to Elasticsearch."
  ],
  mermaidDiagram: `flowchart LR
    App[Application] -->|Async Write| Disk[Local Log File]
    Disk -->|Read| Agent[Fluentd/Logstash Agent]
    Agent -->|Forward| Queue[Kafka Buffer]
    Queue -->|Consume| Indexer[Elasticsearch]
    Indexer -->|Query| UI[Kibana UI]`,
  flashcards: [
    { id: "log-fc1", front: "What is Structured Logging?", back: "Logging in a machine-readable format like JSON for easier querying.", topic: "Observability", difficulty: "Beginner" },
    { id: "log-fc2", front: "Why inject a Correlation ID?", back: "To track a single request's execution path across multiple independent microservices.", topic: "Observability", difficulty: "Intermediate" },
    { id: "log-fc3", front: "What does the ELK stack stand for?", back: "Elasticsearch, Logstash, Kibana. (Often replaced with EFK: Fluentd).", topic: "Observability", difficulty: "Intermediate" },
    { id: "log-fc4", front: "Why is asynchronous logging preferred in production?", back: "It prevents slow disk I/O or network calls from blocking the application's main thread.", topic: "Observability", difficulty: "Advanced" },
    { id: "log-fc5", front: "What is Log Sampling?", back: "Storing only a representative subset of non-critical logs to save storage and network bandwidth.", topic: "Observability", difficulty: "Intermediate" }
  ],
  cheatSheet: {
    title: "Logging Best Practices",
    sections: [
      {
        heading: "Log Levels",
        items: [
          "DEBUG: Detailed info for developers.",
          "INFO: Normal application lifecycle events.",
          "WARN: Unexpected but handled situations.",
          "ERROR: Operation failed, needs investigation.",
          "FATAL: Application crashed."
        ]
      },
      {
        heading: "Best Practices",
        items: [
          "Always use structured logging (JSON).",
          "Include Context (Trace ID, User ID, Timestamp).",
          "Log asynchronously.",
          "Scrub sensitive data (PII, Secrets)."
        ]
      },
      {
        heading: "Tools",
        items: [
          "Aggregation: Fluentd, Logstash, Vector.",
          "Storage/Search: Elasticsearch, Splunk, Datadog."
        ]
      }
    ]
  },
  speedNotes: [
    "Record discrete events.",
    "Use structured JSON format.",
    "Pass correlation IDs everywhere.",
    "Log asynchronously to avoid blocking.",
    "Never log passwords or PII."
  ]
};
