import type { ConceptRevisionContent } from "./types";

export const notificationServiceDesign: ConceptRevisionContent = {
  slug: "notification-service-design",
  title: "Notification Service Design",
  topic: "System Design Case Studies",
  difficulty: "Advanced",
  estimatedMinutes: 30,
  docLinks: [
    { label: "Notification System Case Study", href: "/docs/case-studies/notification-system" },
  ],
  summary: [
    "A notification service delivers messages (Push, SMS, Email) to users across multiple channels.",
    "It requires high throughput for sending messages and reliability to ensure messages aren't lost.",
    "Key components include API Gateway, Notification Servers, Message Queues (Kafka/RabbitMQ), and Third-Party Providers (APNs, FCM, Twilio).",
    "Users' device tokens and preferences must be stored securely and retrieved quickly.",
    "Rate limiting and deduplication are crucial to prevent spamming users.",
    "Asynchronous processing using queues is mandatory to handle traffic spikes and external provider latency."
  ],
  whyAsked: [
    "To test your ability to design a high-throughput, async processing pipeline.",
    "To evaluate how you handle integration with slow/unreliable third-party services.",
    "To see how you manage user state (device tokens, preferences) and prevent system overload."
  ],
  thirtySecondAnswer: "A notification system is fundamentally an asynchronous message processing pipeline. An API receives send requests and pushes them to a message queue. Workers pull from the queue, check user preferences, retrieve device tokens from a database, and route the message to the appropriate third-party provider (APNs, FCM, Twilio). To scale, we use partitioned queues (Kafka) and rate limiters to avoid spam. Retry mechanisms and dead-letter queues handle third-party failures.",
  detailedAnswer: [
    "Async Pipeline: Use message queues (Kafka, SQS) to decouple the frontend API from the workers that call external APIs.",
    "User Preferences: Store opt-outs and channel preferences (e.g., Email vs SMS). Workers must check this before sending.",
    "Device Tokens: Mobile push requires device tokens. Store mapping of UserID to DeviceTokens (1-to-many).",
    "Third-Party Integration: Use Apple Push Notification service (APNs) for iOS, Firebase Cloud Messaging (FCM) for Android, Twilio for SMS, and SendGrid for Email.",
    "Retry & DLQ: External APIs fail. Implement exponential backoff for retries and push unsendable messages to a Dead Letter Queue.",
    "Deduplication & Rate Limiting: Use Redis to track sent messages and ensure users aren't spammed with duplicates or too many alerts."
  ],
  questions: [
    { id: "nsd-q1", question: "What are the main channels of a notification system?", answer: "Push notifications (iOS/Android), SMS, and Email.", topic: "System Design Case Studies", difficulty: "Beginner" },
    { id: "nsd-q2", question: "Why use a message queue in a notification system?", answer: "To decouple receiving requests from sending them, buffering traffic spikes, and handling slow external APIs.", topic: "System Design Case Studies", difficulty: "Beginner" },
    { id: "nsd-q3", question: "What is APNs and FCM?", answer: "Apple Push Notification service and Firebase Cloud Messaging, required to send push notifications to iOS and Android.", topic: "System Design Case Studies", difficulty: "Beginner" },
    { id: "nsd-q4", question: "Where do you store user preferences?", answer: "In a relational or NoSQL database, checked by workers before sending a message.", topic: "System Design Case Studies", difficulty: "Beginner" },
    { id: "nsd-q5", question: "What is a device token?", answer: "A unique identifier generated by Apple/Google that tells APNs/FCM exactly which device to send the push to.", topic: "System Design Case Studies", difficulty: "Beginner" },
    { id: "nsd-q6", question: "How do you handle third-party API rate limits?", answer: "Implement queue throttling and exponential backoff retries when 429 Too Many Requests are received.", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-q7", question: "How do you prevent sending duplicate notifications?", answer: "Use an idempotency key or a Redis cache with a short TTL to track recently sent notification IDs.", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-q8", question: "What is a Dead Letter Queue (DLQ)?", answer: "A queue where messages are sent after they have failed processing multiple times, for later debugging.", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-q9", question: "How do you track open rates or clicks?", answer: "Embed tracking pixels (for email) or unique redirect URLs, which hit an analytics service when triggered.", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-q10", question: "Can a user have multiple device tokens?", answer: "Yes, a user can have multiple phones/tablets. The DB must map UserID to an array of tokens.", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-q11", question: "How do you handle notification templates?", answer: "Store templates in a DB or CDN. Workers fetch the template and hydrate it with user-specific data before sending.", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-q12", question: "Why prioritize push notifications over SMS?", answer: "Push notifications are generally free to send over APNs/FCM, whereas SMS costs money per message via providers like Twilio.", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-q13", question: "How do you design for high availability in this system?", answer: "Deploy across multiple availability zones, use clustered databases, and replicate message brokers (Kafka).", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-q14", question: "How do you handle a sudden spike in a specific topic (e.g., Breaking News)?", answer: "Use dedicated fan-out queues for broadcasting so large broadcasts don't block transactional notifications (like OTPs).", topic: "System Design Case Studies", difficulty: "Advanced" },
    { id: "nsd-q15", question: "How do you ensure notification ordering?", answer: "Strict ordering is hard. If needed, use Kafka partitions keyed by UserID to ensure events for one user are processed in order.", topic: "System Design Case Studies", difficulty: "Advanced" },
    { id: "nsd-q16", question: "What if a user updates their device token while messages are in the queue?", answer: "Workers should fetch the device token from the DB right before sending, rather than queuing the token itself.", topic: "System Design Case Studies", difficulty: "Advanced" },
    { id: "nsd-q17", question: "How do you implement rate limiting per user (e.g., max 5 alerts/day)?", answer: "Use Redis with a sliding window or token bucket algorithm keyed by UserID.", topic: "System Design Case Studies", difficulty: "Advanced" },
    { id: "nsd-q18", question: "What is payload size limitation in Push?", answer: "APNs/FCM strictly limit payload sizes (e.g., 4KB). The system must truncate data or just send a signal to the app to fetch data.", topic: "System Design Case Studies", difficulty: "Advanced" },
    { id: "nsd-q19", question: "How do you gracefully degrade if FCM goes down?", answer: "Failover to SMS or Email if the notification is critical, based on user preferences.", topic: "System Design Case Studies", difficulty: "Advanced" },
    { id: "nsd-q20", question: "How do you batch notifications to improve throughput?", answer: "Consumers read batches from Kafka, query the DB for templates/tokens in bulk, and use bulk endpoints of third-party APIs.", topic: "System Design Case Studies", difficulty: "Advanced" }
  ],
  commonFollowUps: [
    "How do you handle bulk notifications (e.g., sending to 1 million users)?",
    "How do you implement user rate limits (e.g., no more than 3 marketing emails a week)?",
    "How do you monitor and alert on third-party provider outages?"
  ],
  commonMistakes: [
    "Designing a synchronous system where the API waits for APNs/Twilio to respond.",
    "Forgetting to store or check user opt-out preferences.",
    "Not mentioning device tokens or assuming user ID is enough to push to a phone."
  ],
  interviewTraps: [
    "Putting the device token directly in the queue payload. (It can change; query it at send time).",
    "Using a single queue for all priorities. OTPs and Marketing blasts should be on separate queues."
  ],
  tradeoffs: [
    "At-least-once vs At-most-once: Most notification systems prefer at-least-once delivery, accepting rare duplicates over dropped messages.",
    "Payload Data vs Fetch Signal: Sending full data in push avoids client API calls, but risks exceeding size limits. Sending a signal is safer but increases backend load when clients open the app.",
    "Polling vs Webhooks for Status: Polling third parties for delivery status is resource-heavy; using webhooks is preferred."
  ],
  memoryTrick: "Notifications = API -> Queue -> Workers -> 3rd Party APIs.",
  realWorldExamples: [
    "Netflix: Uses massive fan-out to notify users of new shows, utilizing Cassandra and Kafka.",
    "Uber: Sends real-time transactional pushes for ride status, prioritizing latency and reliability."
  ],
  mermaidDiagram: `flowchart TD
    A[Client Service] -->|Send Request| B(API Gateway)
    B --> C(Notification Service)
    C --> D[(Message Broker / Kafka)]
    D --> E(Workers / Dispatchers)
    E <--> F[(User DB / Preferences)]
    E <--> G[(Device Token Cache)]
    E -->|Push| H(APNs / FCM)
    E -->|SMS| I(Twilio)
    E -->|Email| J(SendGrid)
    E -.->|Fails| K[(Dead Letter Queue)]`,
  flashcards: [
    { id: "nsd-fc1", front: "What handles traffic spikes in a notification system?", back: "Message Queues (Kafka/SQS)", topic: "System Design Case Studies", difficulty: "Beginner" },
    { id: "nsd-fc2", front: "What is required to send an iOS push notification?", back: "Device Token & APNs", topic: "System Design Case Studies", difficulty: "Beginner" },
    { id: "nsd-fc3", front: "How do you separate critical OTPs from marketing blasts?", back: "Use different queues (priority queues)", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-fc4", front: "Where do messages go if third-party APIs permanently fail?", back: "Dead Letter Queue (DLQ)", topic: "System Design Case Studies", difficulty: "Intermediate" },
    { id: "nsd-fc5", front: "Should device tokens go in the message queue payload?", back: "No, fetch them from DB right before sending.", topic: "System Design Case Studies", difficulty: "Advanced" }
  ],
  cheatSheet: {
    title: "Notification System",
    sections: [
      {
        heading: "Architecture Pipeline",
        items: [
          "API Gateway -> Event Bus (Kafka) -> Workers -> 3rd Party APIs."
        ]
      },
      {
        heading: "External Dependencies",
        items: [
          "iOS: APNs (Apple Push Notification service).",
          "Android: FCM (Firebase Cloud Messaging).",
          "SMS: Twilio, SNS.",
          "Email: SendGrid, SES."
        ]
      },
      {
        heading: "Best Practices",
        items: [
          "Always check User Preferences/Opt-outs.",
          "Use priority queues (Transactional vs Promotional).",
          "Implement Rate Limiting & Deduplication (Redis)."
        ]
      }
    ]
  },
  speedNotes: [
    "Use queues for async processing.",
    "Store device tokens per user.",
    "Check preferences before sending.",
    "Retries + Dead Letter Queues.",
    "Separate queues by priority."
  ]
};
