import type { ConceptRevisionContent } from "./types";

export const sessions: ConceptRevisionContent = {
  slug: "sessions",
  title: "Sessions",
  topic: "Security",
  difficulty: "Beginner",
  estimatedMinutes: 15,
  docLinks: [
    { label: "Sessions", href: "/docs/security/sessions" },
    { label: "Cookies", href: "/docs/security/cookies" },
    { label: "Authentication", href: "/docs/security/authentication" },
  ],
  summary: [
    "A session is a mechanism for maintaining state across multiple stateless HTTP requests.",
    "Server-side sessions store user data on the server and send a session ID to the client (usually in a cookie).",
    "On subsequent requests, the client sends the session ID, allowing the server to retrieve the session data.",
    "Sessions are commonly used for managing user authentication and shopping carts.",
    "They require server-side storage (memory, database, or cache like Redis).",
  ],
  whyAsked: [
    "To test your understanding of how state is maintained in stateless web protocols.",
    "To evaluate your knowledge of authentication mechanisms.",
    "To see if you understand the trade-offs between server-side state and stateless tokens (JWT).",
  ],
  thirtySecondAnswer: "A session represents a conversation between a client and a server over a period of time. Because HTTP is stateless, servers use sessions to remember clients across multiple requests. This is typically done by generating a unique session ID upon successful login, storing the session data on the server, and sending the ID to the client as a cookie. The client sends this ID back on subsequent requests, allowing the server to identify the user.",
  detailedAnswer: [
    "When a user logs in, the server creates a session and generates a cryptographically secure, unique Session ID.",
    "The session data (e.g., user ID, roles) is stored on the server, often in an in-memory database like Redis for fast access.",
    "The server sends the Session ID back to the client, typically in an HTTP-only, Secure cookie.",
    "For every subsequent request, the browser automatically sends the cookie containing the Session ID.",
    "The server looks up the Session ID in its storage to retrieve the user's data and verify they are authenticated.",
    "When the user logs out or the session expires, the server destroys the session data and the client discards the cookie.",
  ],
  questions: [
    { id: "ses-q1", question: "What is a session in web development?", answer: "A mechanism to store user state across multiple HTTP requests.", topic: "Security", difficulty: "Beginner" },
    { id: "ses-q2", question: "Why are sessions needed in HTTP?", answer: "Because HTTP is inherently stateless.", topic: "Security", difficulty: "Beginner" },
    { id: "ses-q3", question: "Where is session data stored?", answer: "On the server (in memory, database, or a distributed cache like Redis).", topic: "Security", difficulty: "Beginner" },
    { id: "ses-q4", question: "How does the client keep track of a session?", answer: "Usually by storing a unique session ID in a cookie.", topic: "Security", difficulty: "Beginner" },
    { id: "ses-q5", question: "What is a session ID?", answer: "A unique, random string generated by the server to identify a specific session.", topic: "Security", difficulty: "Beginner" },
    { id: "ses-q6", question: "What are the security risks of exposing a session ID?", answer: "Session hijacking; an attacker could impersonate the user.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q7", question: "How can you protect session IDs?", answer: "Use HTTPS, mark cookies as HttpOnly and Secure, and regenerate session IDs on privilege escalation (like login).", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q8", question: "What is session fixation?", answer: "An attack where an attacker tricks a user into authenticating using a session ID known to the attacker.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q9", question: "How do you prevent session fixation?", answer: "By generating a new session ID when the user logs in.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q10", question: "Why use Redis for session storage?", answer: "It's fast, supports TTL (time-to-live) for automatic expiration, and can be shared across multiple server instances.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q11", question: "What is sticky sessions (session affinity)?", answer: "A load balancing technique where a user's requests are always routed to the same server where their session resides.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q12", question: "What is the problem with sticky sessions?", answer: "It makes scaling and fault tolerance difficult; if the server crashes, all its sessions are lost.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q13", question: "How do distributed sessions work?", answer: "Session data is stored in a centralized data store (like Redis or Memcached) accessible by all application servers.", topic: "Security", difficulty: "Advanced" },
    { id: "ses-q14", question: "What happens if the session store goes down?", answer: "All active users might be logged out unless there is a replica or fallback mechanism.", topic: "Security", difficulty: "Advanced" },
    { id: "ses-q15", question: "How is session invalidation handled?", answer: "The server deletes the session record from its storage, immediately revoking access.", topic: "Security", difficulty: "Advanced" },
    { id: "ses-q16", question: "Can a session ID be sent in the URL?", answer: "Yes, but it's highly insecure (URL rewriting) as URLs are often logged or shared.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q17", question: "What is an absolute timeout vs idle timeout?", answer: "Absolute timeout expires the session after a fixed time (e.g., 24 hours), idle timeout expires it after a period of inactivity (e.g., 30 mins).", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q18", question: "How does a server know when to clean up old sessions?", answer: "Through expiration timestamps, background cleanup jobs, or TTL features in databases like Redis.", topic: "Security", difficulty: "Advanced" },
    { id: "ses-q19", question: "What is the tradeoff of large session data?", answer: "It consumes more server memory/storage and increases the load on the session data store.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-q20", question: "Can a user have multiple sessions?", answer: "Yes, for example, logging in from a phone and a laptop creates two separate sessions.", topic: "Security", difficulty: "Beginner" },
  ],
  commonFollowUps: [
    "How would you scale a stateful application that relies on sessions?",
    "Why might you choose JWTs instead of sessions for a microservices architecture?",
    "How do you handle session revocation instantly across a distributed system?",
  ],
  commonMistakes: [
    "Storing business data (like the user's entire profile) in the session instead of fetching it.",
    "Not regenerating the session ID on login, leading to session fixation vulnerabilities.",
    "Relying on in-memory sessions in a load-balanced environment without sticky sessions or a distributed cache.",
  ],
  interviewTraps: [
    "Assuming sessions and cookies are the same thing (cookies are a transport mechanism, sessions are state).",
    "Failing to mention that server-side sessions can be bottlenecked by database lookups on every request.",
  ],
  tradeoffs: [
    "Provides immediate, server-side revocation vs. Requires database/cache lookup on every request.",
    "Easy to implement stateful features (shopping carts) vs. Harder to scale across multiple servers.",
  ],
  comparisonTable: {
    title: "Server-side Sessions vs JWT",
    columns: ["Feature", "Server-side Sessions", "JWT (JSON Web Tokens)"],
    rows: [
      { label: "State", values: ["Stateful (stored on server)", "Stateless (stored on client)"] },
      { label: "Revocation", values: ["Immediate (delete from DB)", "Difficult (requires blocklists)"] },
      { label: "Size", values: ["Small (just an ID)", "Large (contains payload)"] },
      { label: "Scalability", values: ["Harder (requires shared DB)", "Easier (self-contained)"] },
      { label: "Security Risk", values: ["Session Hijacking, CSRF", "Token theft, XSS (if in localStorage)"] },
    ],
  },
  memoryTrick: "Sessions are a VIP list at a club: the server holds the list (session data) and the client holds a wristband (session ID).",
  realWorldExamples: [
    "Banking applications use server-side sessions for high security and immediate revocation upon logout.",
    "E-commerce sites like Amazon use sessions to track anonymous shopping carts before a user logs in.",
  ],
  mermaidDiagram: `sequenceDiagram
    participant Client
    participant Server
    participant Redis(Session Store)
    
    Client->>Server: POST /login (credentials)
    Server->>Server: Verify credentials
    Server->>Redis(Session Store): Save user data, generate Session ID
    Redis(Session Store)-->>Server: OK
    Server-->>Client: Set-Cookie: session_id=abc123 (HttpOnly, Secure)
    
    Note over Client,Server: Subsequent Request
    Client->>Server: GET /dashboard (Cookie: session_id=abc123)
    Server->>Redis(Session Store): Get data for session_id=abc123
    Redis(Session Store)-->>Server: User Data
    Server-->>Client: Return dashboard data`,
  flashcards: [
    { id: "ses-fc1", front: "What is a session?", back: "A mechanism to store user state across multiple HTTP requests on the server.", topic: "Security", difficulty: "Beginner" },
    { id: "ses-fc2", front: "How is a session identified by the client?", back: "By a unique Session ID, typically stored in a cookie.", topic: "Security", difficulty: "Beginner" },
    { id: "ses-fc3", front: "What is Session Fixation?", back: "An attack where an attacker forces a user to use a known session ID.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-fc4", front: "How do you scale server-side sessions?", back: "Use a distributed caching system like Redis or Memcached.", topic: "Security", difficulty: "Intermediate" },
    { id: "ses-fc5", front: "What is the main advantage of sessions over JWT?", back: "Immediate and simple session revocation/invalidation.", topic: "Security", difficulty: "Intermediate" },
  ],
  cheatSheet: {
    title: "Sessions Cheat Sheet",
    sections: [
      {
        heading: "Core Concepts",
        items: [
          "Stateful protocol over stateless HTTP",
          "Session ID: Unique identifier sent to client",
          "Session Data: Kept securely on the server",
        ],
      },
      {
        heading: "Storage Options",
        items: [
          "In-Memory: Fast, doesn't scale horizontally",
          "Database: Slower, scales well",
          "Redis/Memcached: Best balance of speed and scalability",
        ],
      },
      {
        heading: "Security Best Practices",
        items: [
          "Use HttpOnly and Secure flags on cookies",
          "Regenerate session ID on login",
          "Implement idle and absolute timeouts",
        ],
      },
    ],
  },
  speedNotes: [
    "Maintains state over HTTP",
    "Uses Session ID in cookies",
    "Data stored on server",
    "Redis is ideal for storage",
    "Allows instant revocation",
  ],
};
