"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Fuse from "fuse.js";
import { Search, FileText } from "lucide-react";

type IndexEntry = { slug: string; title: string; description: string; body: string };

// Deliberately separate from components/search/search-dialog.tsx (the
// global ⌘K search over the main curriculum): this one only ever searches
// /revision-search-index.json — generated by
// scripts/generate-revision-search-index.mjs from data/revision-hub.ts
// (and, once written, any content/revision-hub/*.mdx files) — so a query
// here can never surface a result from the main docs.
export function RevisionSearch({ placeholder = "Search the Revision Hub..." }: { placeholder?: string }) {
  const [query, setQuery] = useState("");
  const [index, setIndex] = useState<IndexEntry[]>([]);
  const [focused, setFocused] = useState(false);
  const router = useRouter();

  useEffect(() => {
    fetch("/revision-search-index.json")
      .then((r) => r.json())
      .then(setIndex)
      .catch(() => setIndex([]));
  }, []);

  const fuse = useMemo(
    () =>
      new Fuse(index, {
        keys: [
          { name: "title", weight: 0.5 },
          { name: "description", weight: 0.3 },
          { name: "body", weight: 0.2 },
        ],
        threshold: 0.35,
        ignoreLocation: true,
      }),
    [index]
  );

  const results = query.trim() ? fuse.search(query).slice(0, 8) : [];

  function go(slug: string) {
    setQuery("");
    setFocused(false);
    router.push(`/revision-hub/${slug}`);
  }

  return (
    <div className="no-print relative w-full max-w-md">
      <div className="flex items-center gap-2 rounded-lg border border-border dark:border-border-dark bg-surface-raised dark:bg-surface-raised-dark px-3 py-2">
        <Search size={14} className="shrink-0 text-ink-muted dark:text-ink-muted-dark" />
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onFocus={() => setFocused(true)}
          onBlur={() => setTimeout(() => setFocused(false), 120)}
          placeholder={placeholder}
          className="w-full bg-transparent text-sm outline-none placeholder:text-ink-muted dark:placeholder:text-ink-muted-dark"
        />
      </div>
      {focused && query.trim() && (
        <div className="scroll-thin absolute left-0 right-0 top-full z-30 mt-2 max-h-72 overflow-y-auto rounded-lg border border-border dark:border-border-dark bg-surface dark:bg-surface-dark p-1.5 shadow-xl">
          {results.length === 0 && (
            <p className="px-3 py-4 text-center text-sm text-ink-muted dark:text-ink-muted-dark">
              No results for "{query}"
            </p>
          )}
          {results.map((r) => (
            <button
              key={r.item.slug}
              onMouseDown={() => go(r.item.slug)}
              className="flex w-full items-start gap-2.5 rounded-md px-3 py-2 text-left hover:bg-surface-raised dark:hover:bg-surface-raised-dark"
            >
              <FileText size={14} className="mt-0.5 shrink-0 text-signal-500" />
              <span className="min-w-0">
                <span className="block truncate text-sm font-medium text-ink dark:text-ink-dark">
                  {r.item.title}
                </span>
                <span className="block truncate text-xs text-ink-muted dark:text-ink-muted-dark">
                  {r.item.description}
                </span>
              </span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
